### ISSUE TITLE
Query.Deferred exception

### ISSUE THREAD

**Issue by chatoxz** [stevenwanderski/bxslider-4#1098]
trying to to make bxslider on yii2 and i got this error:
`jQuery.Deferred exception: Cannot read property 'indexOf' of undefined TypeError: Cannot read property 'indexOf' of undefined
    at r.fn.init.r.fn.load (http://localhost:8080/js/jquery-3.1.1.min.js:4:19061)
    at HTMLImageElement.<anonymous> (http://localhost:8080/js/jquery.bxslider.js:285:40)
    at Function.each (http://localhost:8080/js/jquery-3.1.1.min.js:2:2815)
    at r.fn.init.each (http://localhost:8080/js/jquery-3.1.1.min.js:2:1003)
    at HTMLImageElement.<anonymous> (http://localhost:8080/js/jquery.bxslider.js:284:12)
    at Function.each (http://localhost:8080/js/jquery-3.1.1.min.js:2:2815)
    at r.fn.init.each (http://localhost:8080/js/jquery-3.1.1.min.js:2:1003)
    at loadElements (http://localhost:8080/js/jquery.bxslider.js:281:50)
    at setup (http://localhost:8080/js/jquery.bxslider.js:271:7)
    at init (http://localhost:8080/js/jquery.bxslider.js:178:7) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
jquery-3.1.1.min.js:4 

Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at r.fn.init.r.fn.load (jquery-3.1.1.min.js:4)
    at HTMLImageElement.<anonymous> (jquery.bxslider.js:285)
    at Function.each (jquery-3.1.1.min.js:2)
    at r.fn.init.each (jquery-3.1.1.min.js:2)
    at HTMLImageElement.<anonymous> (jquery.bxslider.js:284)
    at Function.each (jquery-3.1.1.min.js:2)
    at r.fn.init.each (jquery-3.1.1.min.js:2)
    at loadElements (jquery.bxslider.js:281)
    at setup (jquery.bxslider.js:271)
    at init (jquery.bxslider.js:178)
r.fn.load @ jquery-3.1.1.min.js:4
(anonymous) @ jquery.bxslider.js:285
each @ jquery-3.1.1.min.js:2
each @ jquery-3.1.1.min.js:2
(anonymous) @ jquery.bxslider.js:284
each @ jquery-3.1.1.min.js:2
each @ jquery-3.1.1.min.js:2
loadElements @ jquery.bxslider.js:281
setup @ jquery.bxslider.js:271
init @ jquery.bxslider.js:178
$.fn.bxSlider @ jquery.bxslider.js:1598
(anonymous) @ main.js:26
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2`

**Comment by sn3ka** [comment]
Hi,

you are using the latest version of jQuery (3.1.1).  $(...).load() is deprecated so you have to edit your jquery.bxslider.js or jquery.bxslider.min.js file and find the line with:

`$(this).load(); `

replace it by:

`$(this).trigger('load');`

This should fix your problem.

**Comment by plika10** [comment]
hi,
Thanks sn3ka, problem solved as i wanted to use last jquery 3.1.1 min with my old bxslider version (used since jquery 1.8.2 min ).
now am able to use google.apis link for last release of jquery. 

but somehow, does not work in localhost ?

**Comment by sekmenhuseyin** [comment]
@plika10 did you solve this? if not can you write error messages

**Comment by chatoxz** [comment]
yes it was the version of the jquery. thanks for the answers.

**Comment by Danish8321** [comment]
After using latest version of jQuery file,issue is still there

**Comment by ginsterbusch** [comment]
@Danish8321 Have you tried out the suggested fix in https://github.com/stevenwanderski/bxslider-4/issues/1098#issuecomment-280967672 yet?

**Comment by sn3ka** [comment]
@Danish8321 Well actually it is the last version of bxSlider that your should use with jQuery3.
